mrc-ide-covid-sim:
  name: CovidSim (Imperial)
  origin: Imperial College
  enabled: true
  imageURL: ghcr.io/covid-policy-modelling/covid-sim-connector/covid-sim-connector:latest
  metaURLs:
    code: https://github.com/mrc-ide/covid-sim
    paper: https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf
  description: |
    We consider the feasibility and implications of strategies for COVID-19,
    looking at a range of NPI measures. It is important to note at the outset
    that given SARS-CoV-2 is a newly emergent virus, much remains to be
    understood about its transmission. In addition, the impact of many of the
    NPIs detailed here depends critically on how people respond to their
    introduction, which is highly likely to vary between countries and even
    communities.
  supportedParameters:
    - interventionStrategies
    - r0
  supportedRegions:
    AL:
    AT:
    BA:
    BE:
    BG:
    BY:
    CA:
    CH:
    CR:
    DE:
    DK:
    EE:
    ES:
    FI:
    FR:
    GB:
      - GB
      - GB-LND
    GI:
    GR:
    HR:
    HU:
    IR:
    IS:
    IT:
    LT:
    LU:
    LV:
    MD:
    ME:
    MK:
    MT:
    NG:
    NL:
    NO:
    PL:
    PT:
    RO:
    RS:
    RU:
    SE:
    SI:
    SK:
    UA:
    US:
      - US
      - US-AK
      - US-AL
      - US-AR
      - US-AS
      - US-AZ
      - US-CA
      - US-CO
      - US-CT
      - US-DC
      - US-DE
      - US-FL
      - US-GA
      - US-GU
      - US-HI
      - US-IA
      - US-ID
      - US-IL
      - US-IN
      - US-KS
      - US-KY
      - US-LA
      - US-MA
      - US-MD
      - US-ME
      - US-MI
      - US-MN
      - US-MO
      - US-MS
      - US-MT
      - US-NC
      - US-ND
      - US-NE
      - US-NH
      - US-NJ
      - US-NM
      - US-NV
      - US-NY
      - US-OH
      - US-OK
      - US-OR
      - US-PA
      - US-PR
      - US-RI
      - US-SC
      - US-SD
      - US-TN
      - US-TX
      - US-UT
      - US-VA
      - US-VI
      - US-VT
      - US-WA
      - US-WI
      - US-WV
      - US-WY
